INSERT INTO vets (id, first_name, last_name) VALUES (default, 'Anna', 'Schmidt');
INSERT INTO vets (id, first_name, last_name) VALUES (default, 'Thomas', 'Müller');
INSERT INTO vets (id, first_name, last_name) VALUES (default, 'Julia', 'Fischer');
INSERT INTO vets (id, first_name, last_name) VALUES (default, 'Lukas', 'Weber');
INSERT INTO vets (id, first_name, last_name) VALUES (default, 'Sabine', 'Koch');
INSERT INTO vets (id, first_name, last_name) VALUES (default, 'Markus', 'Becker');

INSERT INTO specialties VALUES (default, 'Radiologie');
INSERT INTO specialties VALUES (default, 'Chirurgie');
INSERT INTO specialties VALUES (default, 'Zahnmedizin');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (default, 'Katze');
INSERT INTO types VALUES (default, 'Hund');
INSERT INTO types VALUES (default, 'Eidechse');
INSERT INTO types VALUES (default, 'Schlange');
INSERT INTO types VALUES (default, 'Vogel');
INSERT INTO types VALUES (default, 'Hamster');

INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Peter', 'Schneider', 'Berliner Allee 12', 'Berlin', '0301234567');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Monika', 'Huber', 'Lindenstraße 5', 'München', '0897654321');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Klaus', 'Bauer', 'Rheinstraße 45', 'Köln', '0221987654');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Eva', 'Richter', 'Marktplatz 3', 'Hamburg', '0402233445');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Jörg', 'Schulz', 'Friedrichstraße 8', 'Stuttgart', '0711123456');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Laura', 'Neumann', 'Poststraße 11', 'Dresden', '0351789456');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Stefan', 'Wagner', 'Kaiserstraße 19', 'Frankfurt', '0692345678');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Birgit', 'Mayer', 'Hauptstraße 99', 'Hannover', '0511765432');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Tobias', 'Klein', 'Bahnhofstraße 10', 'Leipzig', '0341222333');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Nina', 'Schmitt', 'Parkweg 17', 'Bremen', '0421123999');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Helmut', 'Krüger', 'Gartenstraße 20', 'Augsburg', '0821123456');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Kerstin', 'Lorenz', 'Schulstraße 8', 'Erfurt', '0361126789');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Dirk', 'Voigt', 'Dorfstraße 77', 'Regensburg', '0941122233');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Marina', 'Ziegler', 'Am Kirchplatz 3', 'Wiesbaden', '0611234567');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Andreas', 'Horn', 'Am Park 5', 'Freiburg', '0761123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Sabine', 'Böhm', 'Brückenweg 12', 'Bonn', '0228123456');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Michael', 'Lang', 'Ziegelweg 10', 'Münster', '0251123001');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Petra', 'Arnold', 'Weinbergstraße 15', 'Heidelberg', '0622122222');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Torsten', 'Graf', 'Goethestraße 2', 'Jena', '0364123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Anja', 'Fleck', 'Amselweg 9', 'Potsdam', '0331125566');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Günther', 'Möller', 'Rosenweg 22', 'Rostock', '0381123211');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Ines', 'Albrecht', 'Finkenstraße 4', 'Saarbrücken', '0681122233');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Norbert', 'Hahn', 'Waldstraße 10', 'Kiel', '0431127788');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Sonja', 'Meier', 'Im Grund 7', 'Ulm', '0731126644');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Frank', 'Lindner', 'Schlossallee 6', 'Trier', '0651123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Bianca', 'Riedel', 'Bergstraße 19', 'Magdeburg', '0391125566');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Philipp', 'Jansen', 'Steinweg 13', 'Oldenburg', '0441128877');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Sandra', 'Berger', 'Mozartstraße 11', 'Passau', '0851121234');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Tim', 'Schäfer', 'Talstraße 3', 'Lübeck', '0451129988');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Manuela', 'Witte', 'Neuer Weg 25', 'Halle', '0345123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Sven', 'Kühn', 'Ringstraße 17', 'Koblenz', '0261127755');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Angelika', 'Dietrich', 'Hochstraße 5', 'Flensburg', '0461126677');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Holger', 'Franke', 'Kanalstraße 31', 'Zwickau', '0375123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Diana', 'Krebs', 'Bachweg 7', 'Bremerhaven', '0471123456');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Bernd', 'Simon', 'Weststraße 14', 'Bamberg', '0951121122');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Monique', 'Paul', 'Schäfergasse 2', 'Mainz', '0613123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Jonas', 'Heinrich', 'Eichenweg 4', 'Kassel', '0561123456');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Katrin', 'Vogel', 'Sonnenstraße 6', 'Osnabrück', '0541122233');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Dennis', 'Scholz', 'Nordstraße 15', 'Reutlingen', '0712123344');
INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES (default, 'Melanie', 'Ruf', 'Leipziger Straße 8', 'Chemnitz', '0371125566');

INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Minka', '2011-05-10', 1, 1);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Bello', '2013-07-22', 2, 2);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Luna', '2012-03-15', 2, 3);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Rex', '2011-12-01', 2, 3);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Spike', '2010-08-25', 3, 4);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Susi', '2011-02-20', 4, 5);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Tiger', '2014-01-05', 1, 6);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Flocke', '2015-09-12', 5, 7);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Nemo', '2013-11-04', 5, 8);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Fritzi', '2016-06-18', 6, 9);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Keks', '2012-01-30', 6, 10);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Lucky', '2013-04-21', 2, 10);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Milo', '2015-04-18', 2, 11);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Feli', '2017-09-12', 1, 12);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Simba', '2016-11-02', 2, 13);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Lola', '2014-05-25', 1, 14);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Zorro', '2013-08-10', 3, 15);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Bruno', '2018-02-13', 2, 16);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Mimi', '2019-01-05', 1, 17);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Rocky', '2017-06-20', 2, 18);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Hugo', '2020-03-22', 6, 19);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Bonnie', '2015-07-15', 1, 20);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Charlie', '2018-12-30', 2, 21);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Nala', '2016-05-19', 1, 22);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Tapsi', '2019-04-08', 6, 23);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Felix', '2021-03-01', 5, 24);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Shadow', '2017-11-12', 2, 25);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Oskar', '2016-09-09', 4, 26);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Maja', '2013-06-18', 1, 27);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Kira', '2012-02-14', 2, 28);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Chico', '2020-07-07', 5, 29);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Bella', '2021-10-10', 1, 30);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Peanut', '2014-03-11', 6, 31);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Lenny', '2015-01-20', 2, 32);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Fridolin', '2017-08-01', 5, 33);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Greta', '2018-05-05', 1, 34);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Teddy', '2016-07-16', 2, 35);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Speedy', '2019-09-30', 4, 36);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Paula', '2022-01-17', 1, 37);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Maxi', '2021-12-12', 6, 38);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Snoopy', '2020-10-22', 2, 39);
INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES (default, 'Flocki', '2015-02-28', 1, 40);

INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 1, '2014-06-12', 'Impfung – Tollwut');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 2, '2015-08-23', 'Kastration');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 3, '2016-01-17', 'Impfung – Staupe');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 4, '2016-02-20', 'Zahnreinigung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 5, '2017-03-01', 'Röntgenaufnahme');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 6, '2017-07-15', 'Entfernung eines Tumors');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 7, '2018-10-30', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 8, '2019-03-12', 'Schnabelkorrektur');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 9, '2020-04-05', 'Flügelverletzung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 10, '2021-12-10', 'Impfung – Tollwut');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 11, '2022-05-22', 'Krallen schneiden');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 12, '2023-09-14', 'Kastration');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 14, '2020-01-20', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 15, '2020-02-14', 'Ohrenentzündung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 16, '2021-05-25', 'Krallen schneiden');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 17, '2021-06-30', 'Zahnstein entfernt');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 18, '2022-03-12', 'Impfung – Parvovirose');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 19, '2022-07-07', 'Durchfallbehandlung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 20, '2023-04-19', 'Röntgen – Beinbruch');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 21, '2023-06-01', 'Kastration');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 22, '2023-08-16', 'Impfung – Katzenschnupfen');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 23, '2024-01-04', 'Entwurmung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 24, '2024-02-14', 'Impfung – Tollwut');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 25, '2024-04-01', 'Blutuntersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 26, '2024-06-10', 'OP – Fremdkörper');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 27, '2024-07-22', 'Impfung – Leptospirose');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 28, '2024-08-18', 'Augenentzündung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 29, '2024-10-30', 'Allergietest');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 30, '2025-01-03', 'Zahn-OP');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 31, '2025-02-14', 'Impfung – Katzenseuche');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 32, '2025-03-17', 'Krallen schneiden');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 33, '2025-04-25', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 33, '2024-04-25', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 1, '2016-09-15', 'Blutuntersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 1, '2019-03-20', 'Krallen schneiden');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 2, '2016-12-10', 'Zahnsteinbehandlung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 3, '2018-08-05', 'Impfung – Tollwut');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 3, '2020-11-22', 'Durchfallbehandlung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 4, '2018-05-03', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 5, '2018-06-06', 'Verbandswechsel');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 5, '2021-03-30', 'Impfung – Reptilien');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 6, '2019-04-22', 'Röntgenaufnahme');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 6, '2022-06-11', 'Nachsorgeuntersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 7, '2019-08-12', 'Krallen schneiden');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 8, '2020-10-17', 'Schnabelkorrektur');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 9, '2022-09-02', 'Federverlust');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 10, '2023-01-25', 'Impfung – Vogelgrippe');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 11, '2023-05-30', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 12, '2024-02-18', 'Zahnreinigung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 12, '2024-07-12', 'Blutuntersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 13, '2022-11-10', 'Impfung – Parvovirose');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 14, '2021-03-08', 'Augenentzündung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 14, '2023-07-17', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 15, '2022-04-04', 'Blutuntersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 16, '2022-10-20', 'Zahnstein entfernt');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 17, '2023-05-03', 'Ohrenentzündung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 17, '2024-02-09', 'Impfung – Tollwut');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 18, '2023-11-14', 'Kastration');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 19, '2023-08-08', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 20, '2024-12-03', 'Krallen schneiden');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 21, '2024-10-19', 'Nachuntersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 22, '2024-03-16', 'Blutbild');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 23, '2024-05-20', 'Zahnkontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 24, '2024-10-01', 'Impfung – Vogelkrankheit');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 25, '2025-01-25', 'Allgemeine Untersuchung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 26, '2025-02-14', 'Augenentzündung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 27, '2025-03-05', 'Kastration');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 28, '2025-04-12', 'Zahnstein entfernt');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 29, '2025-04-28', 'OP – Hauttumor');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 30, '2025-05-22', 'Routinekontrolle');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 31, '2025-06-01', 'Entwurmung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 32, '2025-06-14', 'Ohrenpflege');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 33, '2025-06-18', 'Impfung – Tollwut');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 34, '2022-12-12', 'Schnabelkorrektur');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 35, '2023-04-25', 'Zahnreinigung');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 36, '2024-02-19', 'Röntgenaufnahme');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 37, '2024-11-30', 'Impfung – Katzenschnupfen');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 38, '2025-01-11', 'Impfung – Katzenseuche');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 39, '2025-02-01', 'Kastration');
INSERT INTO visits (id, pet_id, visit_date, description) VALUES (default, 40, '2025-02-24', 'Impfung – Tollwut');
